public class PartnerPortalUtil {

    public static final String PARTNER_REQUEST_APPLICATION_SUBMISSION = 'Application Submission';
    public static final String PARTNER_REQUEST_PARTNER_CREATION = 'Partner Creation';
    public static final String PER_NEW_USER_PROFILE = 'Potential Partner User Access';
    public static final String PER_FULL_USER_PROFILE = 'Existing Partner User Access';
    public static final String POTENTIAL_PARTNER_PROFILE_NAME = Label.Potential_Partner_User_Profile_Name;
    public static final String GOLD_PARTNER_PROFILE_NAME = Label.Partner_Profile_Name;
    public static final String CUSTOM_GOLDPARTNER_PROFILE_NAME = 'Custom Gold Partner';
    public static final String CUSTOMER_PORTAL_ENDUSER = Label.Customer_Portal_EndUser;
    public static final String CUSTOMER_PORTAL_ENDUSER_RO = Label.Customer_Portal_EndUser_Ro;
    public static final String CUSTOMER_PORTAL_ENDUSER_NA = Label.Customer_Portal_EndUser_No;
    public static final String CUSTOMER_PORTAL_ENDUSER_PP = Label.Customer_Portal_EndUser_PP;
    public static final String CUSTOM_POTENTIAL_PARTNER_USER_PROFILE = 'Genesys Portal Potential Partner'; 
    public static final String MARKETING_PORTAL_PROFILE = Label.Marketing_Community_Profile;
    public static final String PARTNER_COMMUNITY_LOGIN_NEW_PROFILE = 'Genesys Portal Partner';
    public static final String PARTNER_PORTAL_PERMISSIONSET_ID = Label.Partner_Portal_PermissionSet_Id;
    public static final String PARTNER_POTENTIAL_PERMISSIONSET_ID = Label.Partner_Potential_PermissionSet_Id;
    
    public static final String PROFILE_GENESYS_PORTAL_PARTNER_USER   = 'Genesys Portal Partner User';
    public static final String PROFILE_CUSTOM_GOLD_PARTNER_USER      = 'Custom Gold Partner User';
    public static final String PROFILE_GENESYS_PORTAL_PARTNER        = 'Genesys Portal Partner';
    public static final String PROFILE_CUSTOM_GOLD_PARTNER           = 'Custom Gold Partner';
    public static final String PROFILE_PARTNER_COMMUNITY_LOGIN_NEW   = 'Partner Community Login New'; 
    public static final String PARTNER_PORTAL_CONTENT_PUBLICGROUP_ID = Label.Partner_Portal_Content_Group_Id;
    
    public static final String SALESOPS_USER_ID = Label.SalesOps_UserId; 
    public static Boolean isSubmitted=false;
    public static Boolean blnIgnoreDeleteTrigger = false;
    public static Boolean blnIgnoreCalculateMonths = false;
    public static final String GENESYS_HEADER_LOGO = Label.Partner_Portal_Header_Logo;
    public static final String GENESYS_FOOTER_LOGO = Label.Partner_Portal_Footer_Logo;
    public static final String GENESYS_PORTAL_LOGIN_URL = Label.Partner_Portal_login_url; 
    public static final String GENESYS_PORTAL_FPASSWORD_URL = Label.Partner_Portal_pwd_url; 
   
}