/*
    Naresh Kumar    06/17/2013
    Test class for the main controller class SearchPortalCaseResultsController.
*/
@isTest(seeAllData = true)
private class SearchPortalCaseResultsController_Test {
    static testMethod void myUnitTest() {
    /*
        Profile partnerProfile = [SELECT id FROM Profile WHERE Name = 'Genesys Portal End User' LIMIT 1];       
        Account testAccount = TestUtil.createAccounts(1, true)[0];
        Contact testContact = TestUtil.createContacts(1, testAccount, true)[0];
        User testUser = TestCommon.createUser('testU', 'testUser132@test132.com.test', 'Test', 'Test', partnerProfile.id, false);       
        testUser.ContactId = testContact.id;
        insert testUser;
        //Support_Access__c testSA = TestUtil.createSupportAccess(1, true, testContact)[0];
   */
        /*
        System.runAs(testUser){
            SearchPortalCaseResultsController objController = new SearchPortalCaseResultsController();
            objController.fetchSearchResults();
            objController.getItems();
            objController.getCases();
            objController.lazyLoad();
        }
        */
    }
}