@isTest
public class SureTaxTest {
    @isTest
    private static void testSureTaxTest(){
        SureTax objSureTax = new SureTax();
        
        SureTax.ItemTax objItemTax = new SureTax.ItemTax();
        
        SureTax.ItemTax[] itemTaxes = new SureTax.ItemTax[]{};
        SureTax.ItemMessage[] itemMessages = new SureTax.ItemMessage[]{};
        SureTax.ItemTax itemTax = new SureTax.ItemTax();
        SureTax.Address objAddress = new SureTax.Address('02134', '1234');
    }
}