@isTest(seeAllData=true)
private class UpdateServiceContractBatchTest {
	@isTest
    static void testUpdateServiceContractBatch(){
        Database.executeBatch(new UpdateServiceContractBatch());
    } 
    
    @isTest
	static void testUpdateServiceContractBatchScheduler(){
        String cronExp = '0 0 0 3 9 ? 2022';
        Test.startTest();
        // Schedule the test job
        String jobId = System.schedule('testScheduler1', cronExp, new UpdateServiceContractBatchSchedular());
        // Get the information from the CronTrigger API object
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];
        // Verify the expressions are the same
        System.assertEquals(cronExp, ct.CronExpression);
        // Verify the job has not run
        System.assertEquals(0, ct.TimesTriggered);
        // Verify the next time the job will run
        System.assertEquals('2022-09-03 00:00:00', String.valueOf(ct.NextFireTime));
        Test.stopTest();
    } 
}