<?xml version="1.0" encoding="UTF-8"?>
<Workflow xmlns="http://soap.sforce.com/2006/04/metadata">
    <alerts>
        <fullName>General_Rejection_Email_PA</fullName>
        <description>General_Rejection_Email_PA</description>
        <protected>false</protected>
        <recipients>
            <type>creator</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Old_Templates/General_Rejection_Email_PA</template>
    </alerts>
    <alerts>
        <fullName>PKB_Auto_Approve_PA</fullName>
        <description>PKB_Auto_Approve_PA</description>
        <protected>false</protected>
        <recipients>
            <type>creator</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Old_Templates/PKB_Auto_Approve_PA</template>
    </alerts>
    <alerts>
        <fullName>PKB_Coach_Has_Approved_PA</fullName>
        <description>PKB_Coach_Has_Approved_PA</description>
        <protected>false</protected>
        <recipients>
            <type>creator</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Old_Templates/PKB_Coach_Has_Approved</template>
    </alerts>
    <alerts>
        <fullName>PKB_Coach_Has_Rejected_PA</fullName>
        <description>PKB_Coach_Has_Rejected_PA</description>
        <protected>false</protected>
        <recipients>
            <type>creator</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Old_Templates/PKB_Coach_Has_Rejected_PA</template>
    </alerts>
    <alerts>
        <fullName>PKB_Rejection_Email</fullName>
        <description>PKB_Rejection_Email</description>
        <protected>false</protected>
        <recipients>
            <type>creator</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Old_Templates/PKB_Rejection_Email_PA</template>
    </alerts>
    <fieldUpdates>
        <fullName>Product_Advisories_PKB_False</fullName>
        <field>IsVisibleInPkb</field>
        <literalValue>0</literalValue>
        <name>Product Advisories PKB False</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>Product_Advisories_Set</fullName>
        <field>IsVisibleInPrm</field>
        <literalValue>1</literalValue>
        <name>Product Advisories Set Partner</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>Product_Advisories_Set_Customer</fullName>
        <field>IsVisibleInCsp</field>
        <literalValue>0</literalValue>
        <name>Product Advisories Set Customer To False</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>Product_Advisories_Set_Customer_To_False</fullName>
        <field>IsVisibleInCsp</field>
        <literalValue>0</literalValue>
        <name>Product Advisories Set Customer To False</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>Product_Advisories_Set_Customer_To_True</fullName>
        <field>IsVisibleInCsp</field>
        <literalValue>1</literalValue>
        <name>Product Advisories Set Customer To True</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>Product_Advisories_Set_Customer_True</fullName>
        <field>IsVisibleInCsp</field>
        <literalValue>1</literalValue>
        <name>Product Advisories Set Customer True</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>Product_Advisories_Set_Internal</fullName>
        <field>IsVisibleInApp</field>
        <literalValue>1</literalValue>
        <name>Product Advisories Set Internal</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>Product_Advisories_Set_Internal_To_True</fullName>
        <field>IsVisibleInApp</field>
        <literalValue>1</literalValue>
        <name>Product Advisories Set Internal True</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>Product_Advisories_Set_Internal_True</fullName>
        <field>IsVisibleInApp</field>
        <literalValue>1</literalValue>
        <name>Product Advisories Set Internal</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>Product_Advisories_Set_PKB_To_False</fullName>
        <field>IsVisibleInPkb</field>
        <literalValue>0</literalValue>
        <name>Product Advisories Set PKB To False</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>Product_Advisories_Set_Partner_To_True</fullName>
        <field>IsVisibleInPrm</field>
        <literalValue>1</literalValue>
        <name>Product Advisories Set Partner True</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>Product_Advisories_Set_Partner_True</fullName>
        <field>IsVisibleInPrm</field>
        <literalValue>1</literalValue>
        <name>Product Advisories Set Partner to True</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>Product_Advisories_Set_Portal_To_False</fullName>
        <field>IsVisibleInPrm</field>
        <literalValue>0</literalValue>
        <name>Product Advisories Set Portal To False</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>Product_Advisories_Set_Public_True</fullName>
        <field>IsVisibleInPkb</field>
        <literalValue>1</literalValue>
        <name>Product Advisories Set Public True</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>Product_Advisories_Set_Public_to_False</fullName>
        <field>IsVisibleInPkb</field>
        <literalValue>0</literalValue>
        <name>Product Advisories Set Public to False</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>Set_Channel_to_Internal</fullName>
        <field>IsVisibleInApp</field>
        <literalValue>1</literalValue>
        <name>Set Channel to Internal</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
    </fieldUpdates>
    <knowledgePublishes>
        <fullName>Auto_Approval_Publish</fullName>
        <action>PublishAsNew</action>
        <label>Auto_Approval_Publish</label>
        <language>en_US</language>
        <protected>false</protected>
    </knowledgePublishes>
    <rules>
        <fullName>Product Advisories Validated Customer</fullName>
        <actions>
            <name>Product_Advisories_PKB_False</name>
            <type>FieldUpdate</type>
        </actions>
        <actions>
            <name>Product_Advisories_Set_Customer_To_True</name>
            <type>FieldUpdate</type>
        </actions>
        <actions>
            <name>Product_Advisories_Set_Internal_True</name>
            <type>FieldUpdate</type>
        </actions>
        <actions>
            <name>Product_Advisories_Set_Partner_True</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Product_Advisories__kav.ValidationStatus</field>
            <operation>equals</operation>
            <value>Validated Customer</value>
        </criteriaItems>
        <triggerType>onAllChanges</triggerType>
    </rules>
    <rules>
        <fullName>Product Advisories Validated Internal</fullName>
        <actions>
            <name>Product_Advisories_Set_Customer_To_False</name>
            <type>FieldUpdate</type>
        </actions>
        <actions>
            <name>Product_Advisories_Set_Portal_To_False</name>
            <type>FieldUpdate</type>
        </actions>
        <actions>
            <name>Product_Advisories_Set_Public_to_False</name>
            <type>FieldUpdate</type>
        </actions>
        <actions>
            <name>Set_Channel_to_Internal</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Product_Advisories__kav.ValidationStatus</field>
            <operation>equals</operation>
            <value>Validated Internal</value>
        </criteriaItems>
        <triggerType>onAllChanges</triggerType>
    </rules>
    <rules>
        <fullName>Product Advisories Validated Partner</fullName>
        <actions>
            <name>Product_Advisories_Set</name>
            <type>FieldUpdate</type>
        </actions>
        <actions>
            <name>Product_Advisories_Set_Customer</name>
            <type>FieldUpdate</type>
        </actions>
        <actions>
            <name>Product_Advisories_Set_Internal</name>
            <type>FieldUpdate</type>
        </actions>
        <actions>
            <name>Product_Advisories_Set_PKB_To_False</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Product_Advisories__kav.ValidationStatus</field>
            <operation>equals</operation>
            <value>Validated Partner</value>
        </criteriaItems>
        <triggerType>onAllChanges</triggerType>
    </rules>
    <rules>
        <fullName>Product Advisories Validated Public</fullName>
        <actions>
            <name>Product_Advisories_Set_Customer_True</name>
            <type>FieldUpdate</type>
        </actions>
        <actions>
            <name>Product_Advisories_Set_Internal_To_True</name>
            <type>FieldUpdate</type>
        </actions>
        <actions>
            <name>Product_Advisories_Set_Partner_To_True</name>
            <type>FieldUpdate</type>
        </actions>
        <actions>
            <name>Product_Advisories_Set_Public_True</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Product_Advisories__kav.ValidationStatus</field>
            <operation>equals</operation>
            <value>Validated Public</value>
        </criteriaItems>
        <triggerType>onAllChanges</triggerType>
    </rules>
</Workflow>
